// Generated by scripts/generate-schemas.mjs from src/schemas.json — do not edit.
// Run `npm run generate:schemas` after changing schemas.json.

/** Ids of every schema bundled in schemas.json (see docs/SCHEMAS.md). */
export const SCHEMA_IDS = [
  'luna_pinyin',
  'luna_pinyin_fluency',
  'jyut6ping3',
  'jyut6ping3_ipa',
  'double_pinyin',
  'double_pinyin_abc',
  'double_pinyin_flypy',
  'double_pinyin_mspy',
  'double_pinyin_pyjj',
  'wubi86',
  'wubi_pinyin',
  'wubi_trad',
  'pinyin_simp',
  'terra_pinyin',
  'ipa_xsampa',
  'ipa_yunlong',
  'bopomofo',
  'bopomofo_express',
  'combo_pinyin',
  'zyenpheng',
  'sampheng',
  'cangjie5',
  'cangjie5_express',
  'stroke',
  'array30',
  'wugniu_lopha',
  'wugniu',
  'soutzoe',
  'stenotype',
  'scj6',
  'quick5',
] as const

/** A bundled schema id. Custom (self-deployed) schema ids remain plain strings. */
export type SchemaId = (typeof SCHEMA_IDS)[number]
