#!/usr/bin/env node
// Generates from src/schemas.json:
//   - src/engine/schema-ids.ts  (SchemaId union + SCHEMA_IDS, for autocomplete)
//   - docs/SCHEMAS.md           (human-readable table of bundled schemas)
// Run `npm run generate:schemas` after editing schemas.json and commit both.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const schemas = JSON.parse(readFileSync(resolve(root, 'src/schemas.json'), 'utf8'))

// Mirrors buildSchemaMetadata's registration: skip disabled, family members
// inherit the group; family variants fall back to the parent's.
const rows = []
for (const schema of schemas) {
  if (schema.disabled) continue
  rows.push({ ...schema, variants: schema.variants })
  for (const member of schema.family ?? []) {
    if (member.disabled) continue
    rows.push({
      id: member.id,
      name: member.name,
      group: schema.group,
      extended: schema.extended,
      hideComment: schema.hideComment,
      license: schema.license,
      variants: member.variants ?? schema.variants,
    })
  }
}

// --- src/engine/schema-ids.ts ---
const idLines = rows.map((r) => `  '${r.id}',`).join('\n')
writeFileSync(
  resolve(root, 'src/engine/schema-ids.ts'),
  `// Generated by scripts/generate-schemas.mjs from src/schemas.json — do not edit.
// Run \`npm run generate:schemas\` after changing schemas.json.

/** Ids of every schema bundled in schemas.json (see docs/SCHEMAS.md). */
export const SCHEMA_IDS = [
${idLines}
] as const

/** A bundled schema id. Custom (self-deployed) schema ids remain plain strings. */
export type SchemaId = (typeof SCHEMA_IDS)[number]
`,
)

// --- docs/SCHEMAS.md ---
function variantNames(variants) {
  if (variants === undefined) return '简 / 繁'
  if (variants.length === 0) return '—'
  return variants.map((v) => v.name).join(' / ')
}

const table = rows
  .map(
    (r) =>
      `| \`${r.id}\` | ${r.name} | ${r.group} | ${variantNames(r.variants)} | ${
        r.extended ? '✓' : ''
      } | ${r.license ?? ''} |`,
  )
  .join('\n')

writeFileSync(
  resolve(root, 'docs/SCHEMAS.md'),
  `# Bundled schemas

Generated by \`npm run generate:schemas\` from \`src/schemas.json\` — do not
edit by hand.

Pass any id below as \`useRime({ schema })\`. Dictionaries are streamed from
jsdelivr on first use and cached in IndexedDB. "Variants" are the script
variants cycled by \`changeVariant()\` (— means the schema has a single fixed
output script). "Ext." marks schemas supporting the extended charset option.

| Id | Name | Group | Variants | Ext. | License |
| --- | --- | --- | --- | --- | --- |
${table}
`,
)

console.log(`Generated schema-ids.ts and docs/SCHEMAS.md (${rows.length} schemas)`)
